[theme]
# Primary accent color for interactive elements.
primaryColor = "#874545"

# Background color for the main content area.
backgroundColor = "#2a4860"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#874545"

# Color used for almost all text.
textColor = "#fff"
